"use client"
import { Inter } from "next/font/google";
import SideNavbar from "../components/SideNavbar";
import "./globals.css";
import React, { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false);

  const toggleNavbar = () => {
    setIsOpen(!isOpen);
    console.log(isOpen)
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between">
          <SideNavbar isOpen={isOpen} toggleNavbar={toggleNavbar} />
          <main >{children}</main>
        </div>
      </body>
    </html>
  );
}
